name: Standard Ebooks toolset tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install Ubuntu packages
      run: |
        sudo apt update
        sudo apt install calibre default-jre git python3-venv
    - name: Install pipx packages
      run: |
        pipx install .
        pipx inject standardebooks pylint==2.8.2 pytest==7.0.1 mypy==0.812
    - name: Check type annotations with mypy
      run: $PIPX_HOME/venvs/standardebooks/bin/mypy
    - name: Check code with pylint
      run: $PIPX_HOME/venvs/standardebooks/bin/pylint tests/*.py se
    - name: Test with pytest
      run: $PIPX_HOME/venvs/standardebooks/bin/pytest
