name: Standard Ebooks toolset tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install Ubuntu packages
      run: |
        sudo apt update
        sudo apt install python3-pip python3-dev python3-venv libxml2-utils default-jre calibre git
    - name: Install pipx
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --user pipx
        echo $PIPX_BIN_DIR >> $GITHUB_PATH
    - name: Install pipx packages
      run: |
        pipx install .
        pipx inject standardebooks pylint==2.6.0 pytest==6.0.1 mypy==0.790
    - name: Check type annotations with mypy
      run: $HOME/.local/pipx/venvs/standardebooks/bin/mypy
    - name: Check code with pylint
      run: $HOME/.local/pipx/venvs/standardebooks/bin/pylint tests/*.py se
    - name: Test with pytest
      run: $HOME/.local/pipx/venvs/standardebooks/bin/pytest
