name: Standard Ebooks toolset tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install Ubuntu packages
      run: |
        sudo apt-get update
        sudo apt-get install libxml2-utils librsvg2-bin libimage-exiftool-perl default-jre inkscape calibre
    - name: Install pipx
      run: |
        python -m pip install --upgrade pip
        python -m pip install --user pipx
        echo "::add-path::$HOME/.local/bin"
    - name: Install pip packages
      run: |
        pipx install .
        pipx inject standardebooks pylint pytest mypy
    - name: Check type annotations with mypy
      run: $HOME/.local/pipx/venvs/standardebooks/bin/mypy
    - name: Check code with pylint
      run: $HOME/.local/pipx/venvs/standardebooks/bin/pylint tests/*.py se
    - name: Test with pytest
      run: $HOME/.local/pipx/venvs/standardebooks/bin/pytest
